config/routes.rb
Rebeccaholland::Application.routes.draw do
  
  resources :posts do
    member do
      post 'add_comment'
      delete 'remove_comment/:comment_id' => 'posts#remove_comment', :as => 'remove_comment'
    end
  end
  
  get 'tags/' => 'tags#index', :as => :tags
  get 'tags/:id' => 'tags#show', :as => :tag
  
  get 'archives/:year/:month' => 'archives#index', :as => :month_archives
  get 'archives/:year' => 'archives#index', :as => :year_archives

  devise_for :users
  get 'users/:id' => 'users#show', :as => :user
  put 'my-account' => 'users#update', :as => :my_account
  get 'my-account' => 'users#my_account', :as => :my_account
  

  root :to => "posts#index"

end

app/views/shared/_archive_month_link.html.haml
%li= archives_month_link month[:month], month[:count]

app/views/shared/_archive_year_link.html.haml
%li= archives_year_link year[:year], year[:count]
%li
  %ul= render :partial => 'shared/archive_month_link', :collection => year[:months], :as => :month
	

app/views/shared/_recent_comment_link.html.haml
%li #{link_to "#{comment.user.name}", comment.user} commented on #{link_to "#{comment.post.title}", post_path(comment.post, :anchor => "comment_#{comment.id}") }

app/views/shared/_side_bar.html.haml
#sidebar.show-for-medium-up.panel.radius

  .row
    .large-12.medium-6.column

      %nav
        %ul.no-bullet
          %li= link_to 'My Account', my_account_path
          %li= link_to('Create New Post', new_post_path, :class => 'show-for-medium-up') if current_user.can_post 

      %nav
        %h4 Comments
        %ul.no-bullet= render :partial => 'shared/recent_comment_link', :collection => Comment.recent, :as => :comment 

    .large-12.medium-3.column
  
      %nav
        %h4 Archives
        %ul.no-bullet= render :partial => 'shared/archive_year_link', :collection => Post.archives, :as => :year

    .large-12.medium-3.column
      %nav
        %h4 Tags
        %ul.no-bullet= render :partial => 'shared/tag_link', :collection => @tags || Tag.list, :as => :tag 

app/views/shared/_spacer.html.haml
%hr

app/views/shared/_tag_link.html.haml
%li= link_to "#{ tag[:tag] } (#{ tag[:count] })", tag_path(tag)