config/routes.rb
Rebeccaholland::Application.routes.draw do
  
  resources :posts do
    member do
      post 'add_comment'
      delete 'remove_comment/:comment_id' => 'posts#remove_comment', :as => 'remove_comment'
    end
  end
  
  get 'tags/' => 'tags#index', :as => :tags
  get 'tags/:id' => 'tags#show', :as => :tag
  
  get 'archives/:year/:month' => 'archives#index', :as => :month_archives
  get 'archives/:year' => 'archives#index', :as => :year_archives

  devise_for :users
  get 'users/:id' => 'users#show', :as => :user
  put 'my-account' => 'users#update', :as => :my_account
  get 'my-account' => 'users#my_account', :as => :my_account
  

  root :to => "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  module EnumerateEmbeds
    def each_embed(&block)
      reverse.map(&:embed).each do |embed|
        block.call embed
      end
    end
  end
  
	belongs_to :user
	has_many :comments, :dependent => :destroy
	has_many :tags,     :dependent => :destroy 
	has_many :photos,   :dependent => :destroy, :class_name => 'Image'
	has_many :videos,   :dependent => :destroy, :extend => EnumerateEmbeds
	
	validates :title, :presence => true
	
	accepts_nested_attributes_for :photos, :allow_destroy => true, :reject_if => lambda { |i| i[:url].blank? }
	accepts_nested_attributes_for :videos, :allow_destroy => true, :reject_if => lambda { |v| v[:embed].blank? }
	
	default_scope includes('comments').order('created_at desc')
	
	def self.find_by_tag(tag)
	  posts = where('id in (select post_id from tags where tag like ?)', tag).order('id DESC').includes(:comments, :tags)
	end
	
	def self.archives
	  
	  posts = select('created_at').order('id DESC')
	  
    archive = []

	  year_count = posts.group_by{ |post| post.created_at.beginning_of_year }.map do |year| 
	    
      months = posts.select{ |p| p.created_at.beginning_of_year ==  year[0] }.group_by{ |p| p.created_at.beginning_of_month }.map do |month| 
        { :month => month[0], :count => month[1].count }
      end

      archive << { 
        :year => year[0], 
        :count => year[1].count, 
        :months => months.sort_by{ |m| m[:month] }.reverse
      }      
      
    end
    
    archive.sort_by{ |a| a[:year] }.reverse
    
	end
	
	def self.find_by_year(year)
	  where(:created_at => (year)..(year + 1.year)).order('created_at').includes(:comments, :user, :tags)
	end
	
	def self.find_by_month(month)
  	where(:created_at => (month)..(month + 1.month)).order('created_at').includes(:comments, :user, :tags)
	end

	def to_param
		"#{self.id} #{self.title}".parameterize 
	end

	def date_pretty
		self.created_at.strftime("%A #{self[:created_at].day.ordinalize} %B %Y")
	end
	
	def previous_post
	  @previous_post ||= self.class.where("created_at < ?", created_at).order("created_at desc").first
	end

	def next_post
	  @next_post ||= self.class.where("created_at > ?", created_at).order("created_at asc").first
	end
		
	def allowed_to_edit_or_delete?(current_user)
	  current_user.nil? ? false : (current_user.is_super_user || current_user.id == self.user_id )
	end
	
end

# == Schema Information
#
# Table name: posts
#
#  id         :integer         not null, primary key
#  user_id    :integer
#  title      :string(255)
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/posts_controller.rb
class PostsController < SideBarController  
  
  before_filter :can_post, :only => [:new, :edit, :create, :update, :destroy]   
  before_filter :load_post!, :only => [:show, :edit, :update, :destroy, :add_comment, :remove_comment]
  before_filter :can_edit, :only => [:edit, :update, :destroy]

  # GET /posts
  def index
    
    @posts = Post.paginate(:page => params[:page], :per_page => 5).includes(:comments, :photos, :videos)
    
    return render :partial => @posts, :spacer_template => 'shared/spacer' if request.xhr?
    
  end

  # GET /posts/1
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build

    1.times { @post.videos.build }
    10.times { @post.photos.build }
  end

  # GET /posts/1/edit
  def edit 
    1.times { @post.videos.build }
    10.times { @post.photos.build }
  end

  # POST /posts
  def create
    
    @post = current_user.posts.build params[:post] 
    params[:tags_list].split(',').select(&:present?).map(&:strip).each do |tag|
      @post.tags.build :tag => tag
    end  
  
    if @post.save
      redirect_to @post, :notice => "#{@post.title} was created."
    else  
      flash[:error] = @post.errors.full_messages.to_sentence 
      render :action => 'new'
    end
    
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
        
    params[:tags_list].split(',').select(&:present?).map(&:strip).each do |tag|
      @post.tags.find_or_create_by_tag tag
    end
   
    if @post.update_attributes params[:post] 
      redirect_to @post, :notice => "#{@post.title} was updated."
    else      
      flash[:error] = @post.errors.full_messages.to_sentence
      render url_for(:action => 'edit') 
    end
    
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    
    @post.destroy
    redirect_to posts_path, :notice => "#{ @post.title } deleted"
    
  end
  
  def add_comment
    
    if @comment = @post.comments.create(:body => params[:comment][:body], :user => current_user)
      
      if request.xhr?
        render :partial => 'posts/comment', :object => @comment
      else
        redirect_to @post, :notice => 'Comment added'
      end
      
    else
      
      if request.xhr?
        render :json => @comment, :status => 400
      else
        render 'show'
      end
      
    end
    
  end
  
  def remove_comment
    
    comment = @post.comments.find params[:comment_id]
    comment.delete if comment.allowed_to_delete?(current_user)
    
    if request.xhr?
      render :nothing => true
    else  
      redirect_to @post, :notice => 'Comment deleted'
    end
    
  end

private

  def can_post
    redirect_to posts_path unless current_user.can_post
  end

  def load_post!
    @post = Post.includes(:comments, :user, :tags, :videos, :photos).find(params[:id])
  end

  def can_edit
    redirect_to @post unless @post.user_id == current_user.id
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  
	def tags_list(tags_list)

		tags_list.map{|t| link_to t.tag, tag_path(t) }.join(', ').html_safe

	end

end

app/views/posts/_comment.html.haml
.row.comment{ :id => ['comment', comment.id] }
  .medium-10.column
    
    %blockquote
      = simple_format comment.body
      %cite #{ link_to comment.user.name, user_path(comment.user) } on #{ comment.date_pretty }

    %p= link_to('Delete', remove_comment_post_path(@post, comment), :class => 'button tiny alert', :method => :delete, :confirm => "Are you sure?", :remote => true) if comment.allowed_to_delete?(current_user)

  .medium-2.column.hide-for-small-only
    %a{ :href => user_path(comment.user) }= image_tag "avatars/#{ comment.user.avatar }", :alt => comment.user.name, :class => 'avatar'

app/views/posts/_form.html.haml
= form_for @post do |f|

  - if @post.errors.any?
    .alert.alert-error
      %button.close{ :type => 'button', :data => { :dismiss => 'alert' } } &times;
      %h3 #{ pluralize(@post.errors.count, 'error') } prohibited this post from being saved:
      %ul
        -  @post.errors.full_messages.each do |msg|
          %li= msg

  = f.label :title, "This post's title"
  = f.text_field :title, :required => true

  = f.label :body, "This post's contents"
  = f.text_area :body

  = label_tag :tags_list, "This post's tags"
  = text_field_tag :tags_list, @post.tags.map(&:tag).join(", ")

  = f.fields_for :videos do |video_form|	
    %fieldset
      %legend Video
  	
      = video_form.label :embed
      ~ video_form.text_area :embed
      %label.checkbox
        = video_form.check_box '_destroy'
        Delete

  %dl.tabs{ 'data-tab' => ''}    
    %dd.active
      %a{ :href => '#photos-picasa' } Picasa
    %dd
      %a{ :href => '#photos-embed' } Direct Embed

  .tabs-content
    #photos-embed.content
      = f.fields_for :photos do |image_form|
        %fieldset
          %legend Photo
          = image_form.label :url
          ~ image_form.text_area :url
          = image_form.label :thumbnail
          ~ image_form.text_area :thumbnail
          %label.checkbox
            = image_form.check_box '_destroy'
            Delete

    #photos-picasa.content.active  
      
      = label :picasa_album, 'Album'
      = select_tag :picasa_album, nil, :prompt => "Select"
        
      %ul#photos-picasa-gallery.small-block-grid-2.medium-block-grid-3

  = f.submit :class => 'button large'

= content_for :javascripts do
  = javascript_include_tag 'picasa_importer.js'

app/views/posts/_post.erb
<article id="post">
	<h2><%= link_to post.title, post %></h2>
	<h4><time datetime="<%= post.created_at %>"><%= post.date_pretty %></time></h4>
	<div id="body">
		<%= simple_format auto_link post.body %>

		<% post.videos.each do |video| %>
			<%= raw video.embed %>
		<% end %>

		<% post.images.each do |image| %>
			<%= raw image.url %>
		<% end %>
	</div>
	<div class="small">
		<p>
			<%= link_to_if show_view_link, "View", post, :class => 'view' do end %>
			<%= link_to_if current_user.is_super_user || post.user_id == current_user.id, 'Edit', edit_post_path(post) do end  %>
			<%= link_to_if current_user.is_super_user || post.user_id == current_user.id, 'Delete', post, :method => :delete, :confirm => "Are you sure?" do end  %>
		</p>
		<p>
			Comments: <%= link_to post.comments.count, post_path(post, :anchor => 'comments') %> | 
			Posted by: <%= link_to post.user.name, post.user %>
		</p>
		<p>
			Tags: <%= raw tags_list(post.tags)%> 
		</p>
	</div>
</article>

app/views/posts/_post.html.haml
%article

  %a{ :href => post_path(post) }
    %h1= post.title

  :markdown
    #{ post.body }

  - if post.videos.any?
    %section.videos
      - post.videos.each_embed do |video|
        .flex-video= video.html_safe
  
  - if post.photos.any?
    %section.photos
      %ul.medium-block-grid-3.large-block-grid-3.clearing-thumbs{ 'data-clearing' => '' }
        - post.photos.each do |photo|
          %li
            %a.th{ :href => photo.url }= image_tag photo.thumbnail
  
  %p.text-center
    = link_to "Posted #{ post.date_pretty }", post
    |
    = link_to pluralize(post.comments.length, 'Comment'), post_path(post, :anchor => 'comments')
  

app/views/posts/_teaser.erb
<% if post_counter.even? %>
<div class="teaser clearfix">
<% end %>
	<% if post_counter.even? %>
	<div>
	<% else %>
	<div class="teaser_right">
	<% end %>
		<h3><%= link_to post.title, post %></h3>
		<time datetime="<%= post.created_at %>"><%= post.date_pretty %></time>
		<article>
			<%= simple_format truncate post.body, :length => 100 %>
		</article>
		<div class="small">
			<p>
				<%= link_to "View", post, :class => 'view' %>
			</p>
		</div>
	</div>
<% if post_counter.odd? %>
</div>
<% end %>

app/views/posts/edit.html.haml
- @title= "Editing #{ @post.title }"

.page-header
  %h1 Editing "#{@post.title}"

= render 'form'

%p #{link_to 'Show', @post} | #{link_to 'All posts', posts_path}

app/views/posts/index.html.haml
= render :partial => @posts, :spacer_template => 'shared/spacer'
  
.pagination-centered= will_paginate @posts, :renderer => FoundationPagination::Rails, :inner_window => 2

app/views/posts/new.html.haml
- @title = 'Create new post'

.page-header
  %h1 Create new post

= render 'form'

%p= link_to 'All posts', posts_path

app/views/posts/show.html.haml
- @title = @post.title

= render :partial => @post

- if @post.tags.any?
  %p
    Tags:
    = @post.tags.map{ |t| link_to t.tag, tag_path(t) }.join(', ').html_safe

- if @post.allowed_to_edit_or_delete?(current_user)
  %ul.button-group.right
    %li= link_to 'Edit', edit_post_path(@post), :class => 'button tiny secondary'
    %li= link_to 'Delete', post_path(@post), :method => :delete, :confirm => 'Are you sure?', :class => 'button tiny alert'

%hr

#comments
  %h3= pluralize @post.comments.size, 'comment'
  = render :partial => 'comment', :collection => @post.comments


  = form_for @comment, :url => add_comment_post_path(@post), :remote => true do |f|
    = f.label :body, 'Add your comment'
    ~ f.text_area :body
    = submit_tag "Post Comment", :class => 'button'